# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'sbs/pipeline-test'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: 'buildAndPush'
          repository: 'sbs/pipeline-test'
          Dockerfile: '**/Dockerfile'
          containerRegistry: $(containerRegistry)
          tags: |
            $(tag)
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'plattform-cluster-serviceconnection'
          namespace: 'sbs-dev'
          manifests: '**/kubernetes.yml'
          containers: '$(containerRegistry)/$(imageName):$(tag)'

