# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'sbs/pipeline-test'
  containerRegistry: 'plattform.azurecr.io'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:    
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'
      steps:

      - task: Npm@1
        inputs:
          command: 'install'
          customEndpoint: 'NPM NRK'

      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: 'buildAndPush'
          repository: 'sbs/pipeline-test'
          Dockerfile: '**/Dockerfile'
          containerRegistry: $(containerRegistry)
          tags: |
            $(tag)

      - bash: |
          #/bin/bash
          BuildId="$BUILD_BUILDID"
          sed -i "s/BUILDNUMBER/$BuildId/g" ./kubernetes.yml
          cat ./kubernetes.yml
        displayName: 'Update manifest with build number'

      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'plattform-aks-platform-intern-we-sbs-dev-1585824333532'
          namespace: 'sbs-dev'
          manifests: '**/kubernetes.yml'
          containers: '$(containerRegistry)/$(imageName):$(tag)'
    